DROP TABLE IF EXISTS balances CASCADE;

CREATE TABLE balances(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  coin_id INTEGER REFERENCES coins(id) NOT NULL,
  balance DOUBLE PRECISION NOT NULL
)